#ifndef _SCENE_CONTEXT_H_
#define _SCENE_CONTEXT_H_
#include <3ds.h>
#include <citro3d.h>

// These headers are generated by the build process
#include "vshader_shbin.h"
#include "types.h"

struct SceneContext {
	shaderProgram_s program;
	DVLB_s* vshader_dvlb;
	int uLoc_projection;
    VBOEntry *vbo;
    C3D_Mtx projection;
    C3D_Tex spritesheet_tex;

    void InitShader();
    ~SceneContext();
};

#endif
